fix: constrain node-js
node-js@22.4.0 did not build due to
```
../deps/v8/src/compiler/wasm-compiler.cc:8620:59: error: too many
initializers for 'v8::internal::wasm::WrapperCompilationInfo::<unnamed
union>'
```

we opt against debugging this issue and constrain the version for now.
In the previous container, node-js@18.12.1 was installed.

Change-Id: I22dcd2a97afba94bc3a06d19c451f0e8445b666f